baseURL = "https://www.mitre-drivers.khulnasoft.com/"
title = "mitigate-drivers"
enableRobotsTXT = true
theme = ["compose"] # loading from local
enableGitInfo = true
# Google Analytics
googleAnalytics = "G-33C5VXLWPQ"
[outputs]
  home = ["HTML", "RSS","JSON"]
